### ISSUE TITLE
Repl Support

### ISSUE THREAD

**Issue by ShipmasterKyle** [MikeDev101/cloudlink#38]
I only got into cloudlink recently but I'd like to think ik enough to atleast setup a server. See I'm using repl (repl? replit? the name is so inconsistent) and I've built my project using the example py file but when I try to push the server to anything other than localhost, I get errors. Here they are:

`CloudLink v0.1.7.6
Set MOTD to "CloudLink test".
Running server on ws://0.0.0.0:3000/
----------------------------------------
Exception happened during processing of request from ('172.18.0.1', 58234)
Traceback (most recent call last):
  File "/usr/lib/python3.8/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/websocket_server/websocket_server.py", line 271, in __init__
    StreamRequestHandler.__init__(self, socket, addr, server)
  File "/usr/lib/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/websocket_server/websocket_server.py", line 282, in handle
    self.handshake()
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/websocket_server/websocket_server.py", line 433, in handshake
    assert headers['upgrade'].lower() == 'websocket'
KeyError: 'upgrade'
----------------------------------------`

**Comment by showierdata9978** [comment]
Thats ment to happen

**Comment by ShipmasterKyle** [comment]
> Thats ment to happen

Ok but the server can't connect. How do I fix it?

**Comment by showierdata9978** [comment]
replit is odd , i have that problem myself.

**Comment by TermOfficial** [comment]
in server_example.py
change cl.server() to cl.server(ip="0.0.0.0")
Hope this helps!

**Comment by ShipmasterKyle** [comment]
> in server_example.py change cl.server() to cl.server(ip="0.0.0.0") Hope this helps!

I did that. Thats when I get that issue.

For now I've simply made a fork of CloudLink and added the WebSocket Server it creates. It seems to work.
